### ISSUE TITLE
Autologin not working

### ISSUE THREAD

**Issue by wilderyns** [namreeb/wowreeb#10] opened 2018-07-16 01:55 UTC
I got autologin working for a day, following all the instructions with regards to encrypting your password, pasting that into config. 

However, I tried to use autologin again and this time WoW opens, but instead of the usual "connecting" followed by "success" dialogue, an empty dialogue box shows, with only the cancel button (pictured). I have redownloaded wowreeb, tried both x64 and x32, remade by config file, deleted both WDB and WTF, run wowreeb as admin, set WoW to run as admin, and tried different servers. None of that worked. 

I'm running Windows 10 and trying to get wowreeb to start WoW 1.12. I am able to login if I open WoW normally and type my password. 

Also attached is my [config.txt](https://github.com/namreeb/wowreeb/files/2196362/config.txt) as a .txt (as that's all Github allows), with my username and password removed.

![capture](https://user-images.githubusercontent.com/966641/42740704-c6b60efa-88a2-11e8-8099-a212a553f2cb.JPG)

**Comment by namreeb** [comment] 2018-07-16 04:39
Interesting. You’re the second person to say this. I will try and look at it more closely. Can you alter your configuration file to enable the console and post what the console output is when you see this blank status box?  To open the console press ` and note that you can use your mouse to drag the console window down to fit more output on the screen.

**Comment by wilderyns** [comment] 2018-07-16 12:30
Here you go!
![capture](https://user-images.githubusercontent.com/966641/42758733-623f0e04-88fc-11e8-9dd7-c5f0d84f4bb2.JPG)

**Comment by joao-fidalgo** [comment] 2018-07-16 14:40
Interesting, i have the same problem on my laptop, even tho it works perfectly on my desktop.

**Comment by wilderyns** [comment] 2018-07-16 15:23
Indeedy. Didn't change a thing, no weird driver updates or even a restart of my PC. Just kinda stopped.

**Comment by namreeb** [comment] 2018-07-16 22:28
This appears to have been caused by the server maintenance alert that was published by Blizzard earlier today.  We are beginning our login attempt before it arrives.  It is arriving before the login attempt completes, and once that happens the login attempt is silently aborted.  I am still trying to find the best way to work around this.  As a workaround, you can temporarily add the following to `%SystemRoot%\system32\drivers\etc\hosts`:

`127.0.0.1 launcher.worldofwarcraft.com`

**Comment by wilderyns** [comment] 2018-07-17 00:28
Yep, that did the trick. Quick and dirty workaround might be a batch file included to rewrite hosts if the user experiences this problem, or include a temporary rewrite of the host file upon launching, which then removes the entry once logged in? Either way,  cheers for the help, and the launcher itself!

**Comment by namreeb** [comment] 2018-07-17 00:31
Ultimately we want to keep the server alert message, if for no other reason than that some servers may use it, now or in the future.  With that in mind, note to self: #11

**Comment by namreeb** [comment] 2018-07-17 02:07
Fixed in release [3.1](https://github.com/namreeb/wowreeb/releases/tag/3.1).

**Closed as completed by namreeb** 2018-07-17 02:07 UTC
Labels: bug
